version: '3.8'
services:
  node:
    container_name: node
    restart: always
    build: ./server
    ports:
      - '3000:3000'
    links:
      - db
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - TZ=America/Sao_Paulo
    ports:
      - '5440:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  web:
    container_name: web
    restart: always
    build: ./web
    ports:
      - '5137:5137'
    links:
      - node
    depends_on:
      - node

volumes:
  db:
    driver: local