version: '3.8'
services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - TZ=America/Sao_Paulo
    ports:
      - '5440:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local